/**
 * Centralized Supabase query functions for the Helplytics AI app.
 *
 * Each function handles the Supabase call and returns typed data
 * matching the existing interfaces in mockData.ts, or throws on error.
 */
import { supabase } from "@/integrations/supabase/client";
import type {
  HelpRequest,
  ActivityEntry,
  Message,
  Notification,
  UserProfile,
  RequestStatus,
  Urgency,
} from "@/data/mockData";

// ─── Help Requests ───────────────────────────────────────────────

export interface HelpRequestFilters {
  status?: RequestStatus;
  category?: string;
  urgency?: Urgency;
  reporterId?: string;
  from?: string;
  to?: string;
}

/** Map a Supabase help_requests row + joined activity to our HelpRequest type */
function mapRequest(row: any): HelpRequest {
  return {
    id: row.id,
    title: row.title,
    description: row.description,
    category: row.category ?? "Other",
    tags: row.tags ?? [],
    urgency: row.urgency ?? "Medium",
    status: row.status === "Resolved" ? "Solved" : (row.status ?? "Open"),
    helperIds: (row.help_request_helpers ?? []).map((h: any) => h.helper_id),
    location: row.location ?? "",
    skillsNeeded: row.skills_needed ?? [],
    reporterId: row.reporter_id ?? undefined,
    reporterName: row.reporter_name ?? undefined,
    reporterContact: row.reporter_contact ?? undefined,
    photoUrl: row.photo_url ?? undefined,
    reportedAt: row.reported_at,
    solvedAt: row.resolved_at ?? undefined,
    resolutionNotes: row.resolution_notes ?? undefined,
    activity: (row.help_request_activity ?? []).map((a: any): ActivityEntry => ({
      id: a.id,
      at: a.at,
      who: a.who,
      action: a.action,
    })),
  };
}

export async function fetchHelpRequests(
  filters?: HelpRequestFilters,
): Promise<HelpRequest[]> {
  let query = supabase
    .from("help_requests")
    .select("*, help_request_helpers(helper_id), help_request_activity(id, at, who, action)")
    .order("reported_at", { ascending: false });

  if (filters?.status) {
    query = query.eq("status", filters.status);
  }
  if (filters?.category) {
    query = query.eq("category", filters.category);
  }
  if (filters?.urgency) {
    query = query.eq("urgency", filters.urgency);
  }
  if (filters?.reporterId) {
    query = query.eq("reporter_id", filters.reporterId);
  }
  if (filters?.from) {
    query = query.gte("reported_at", filters.from);
  }
  if (filters?.to) {
    const toDate = new Date(filters.to);
    toDate.setHours(23, 59, 59, 999);
    query = query.lte("reported_at", toDate.toISOString());
  }

  const { data, error } = await query;
  if (error) throw error;
  return (data ?? []).map(mapRequest);
}

export async function fetchHelpRequestById(
  id: string,
): Promise<HelpRequest | null> {
  const { data, error } = await supabase
    .from("help_requests")
    .select("*, help_request_helpers(helper_id), help_request_activity(id, at, who, action)")
    .eq("id", id)
    .maybeSingle();

  if (error) throw error;
  return data ? mapRequest(data) : null;
}

export async function createHelpRequest(input: {
  title: string;
  description: string;
  category: string;
  tags: string[];
  urgency: Urgency;
  location: string;
  skillsNeeded: string[];
  reporterId: string;
  reporterName?: string;
  reporterContact?: string;
}): Promise<HelpRequest> {
  // Insert the help request — code is auto-generated by the DB trigger
  const { data: row, error } = await supabase
    .from("help_requests")
    .insert({
      title: input.title,
      description: input.description,
      category: input.category,
      tags: input.tags,
      urgency: input.urgency,
      location: input.location,
      skills_needed: input.skillsNeeded,
      reporter_id: input.reporterId,
      reporter_name: input.reporterName ?? null,
      reporter_contact: input.reporterContact ?? null,
      code: "", // trigger will overwrite
    })
    .select("*, help_request_helpers(helper_id), help_request_activity(id, at, who, action)")
    .single();

  if (error) throw error;

  // Log the initial activity
  await supabase.from("help_request_activity").insert({
    request_id: row.id,
    who: input.reporterName ?? "Anonymous",
    action: "Posted help request",
  });

  return mapRequest(row);
}

export async function updateHelpRequestStatus(
  id: string,
  status: RequestStatus,
  actor: string,
  notes?: string,
): Promise<void> {
  const updatePayload: Record<string, any> = { status };
  if (status === "Solved") {
    updatePayload.resolved_at = new Date().toISOString();
    if (notes) updatePayload.resolution_notes = notes;
  }

  const { error } = await supabase
    .from("help_requests")
    .update(updatePayload)
    .eq("id", id);
  if (error) throw error;

  await supabase.from("help_request_activity").insert({
    request_id: id,
    who: actor,
    action: status === "Solved"
      ? `Marked as solved${notes ? `: ${notes}` : ""}`
      : `Status set to ${status}`,
  });
}

export async function deleteHelpRequest(id: string): Promise<void> {
  const { error } = await supabase
    .from("help_requests")
    .delete()
    .eq("id", id);
  if (error) throw error;
}

export async function offerHelpOnRequest(
  requestId: string,
  userId: string,
  userName: string,
): Promise<void> {
  // Insert into help_request_helpers (the join table uses helper_id
  // referencing helpers.id — but for user-based helpers we use the
  // user's auth.uid() as the helper_id if they aren't in the legacy
  // helpers table). This requires the helper to exist in `helpers`.
  //
  // For a cleaner approach, insert the offer and update status:
  const { error: insertError } = await supabase
    .from("help_request_helpers")
    .insert({ request_id: requestId, helper_id: userId })
    .select()
    .maybeSingle();

  // Ignore unique constraint violations (already offered)
  if (insertError && !insertError.message.includes("duplicate")) {
    throw insertError;
  }

  // Update request status to In Progress if currently Open
  await supabase
    .from("help_requests")
    .update({ status: "In Progress" })
    .eq("id", requestId)
    .eq("status", "Open");

  // Log activity
  await supabase.from("help_request_activity").insert({
    request_id: requestId,
    who: userName,
    action: "Offered to help",
  });
}

// ─── Messages ────────────────────────────────────────────────────

export async function fetchMessages(userId: string): Promise<Message[]> {
  // RLS automatically filters to messages where user is sender or recipient
  const { data, error } = await supabase
    .from("messages")
    .select("*")
    .order("sent_at", { ascending: true });

  if (error) throw error;

  return (data ?? []).map((row): Message => ({
    id: row.id,
    requestId: row.request_id,
    fromUserId: row.from_user_id,
    toUserId: row.to_user_id,
    body: row.body,
    sentAt: row.sent_at,
  }));
}

export async function sendMessage(input: {
  requestId: string;
  fromUserId: string;
  toUserId: string;
  body: string;
}): Promise<Message> {
  const { data, error } = await supabase
    .from("messages")
    .insert({
      request_id: input.requestId,
      from_user_id: input.fromUserId,
      to_user_id: input.toUserId,
      body: input.body,
    })
    .select()
    .single();

  if (error) throw error;

  return {
    id: data.id,
    requestId: data.request_id,
    fromUserId: data.from_user_id,
    toUserId: data.to_user_id,
    body: data.body,
    sentAt: data.sent_at,
  };
}

// ─── Notifications ───────────────────────────────────────────────

export async function fetchNotifications(
  userId: string,
): Promise<Notification[]> {
  // RLS filters to user's own notifications
  const { data, error } = await supabase
    .from("notifications")
    .select("*")
    .order("created_at", { ascending: false });

  if (error) throw error;

  return (data ?? []).map((row): Notification => ({
    id: row.id,
    userId: row.user_id,
    type: row.type as Notification["type"],
    text: row.text,
    read: row.read,
    createdAt: row.created_at,
    requestId: row.request_id ?? undefined,
  }));
}

export async function markNotificationRead(id: string): Promise<void> {
  const { error } = await supabase
    .from("notifications")
    .update({ read: true })
    .eq("id", id);
  if (error) throw error;
}

export async function markAllNotificationsRead(
  userId: string,
): Promise<void> {
  const { error } = await supabase
    .from("notifications")
    .update({ read: true })
    .eq("user_id", userId)
    .eq("read", false);
  if (error) throw error;
}

export async function insertNotification(input: {
  userId: string;
  type: Notification["type"];
  text: string;
  requestId?: string;
}): Promise<void> {
  await supabase.from("notifications").insert({
    user_id: input.userId,
    type: input.type,
    text: input.text,
    request_id: input.requestId ?? null,
  });
}

// ─── Profiles ────────────────────────────────────────────────────

export interface ProfileRow {
  id: string;
  name: string;
  email: string;
  org_name: string;
  skills: string[];
  interests: string[];
  location: string;
  trust_score: number;
  badges: string[];
  contributions_count: number;
}

function mapProfile(row: ProfileRow): UserProfile {
  return {
    id: row.id,
    name: row.name,
    email: row.email,
    role: "Student", // will be overridden by caller if needed
    skills: row.skills ?? [],
    interests: row.interests ?? [],
    location: row.location ?? "",
    trustScore: row.trust_score ?? 50,
    badges: row.badges ?? [],
    contributionsCount: row.contributions_count ?? 0,
  };
}

export async function fetchProfile(userId: string): Promise<UserProfile | null> {
  const { data, error } = await supabase
    .from("profiles")
    .select("*")
    .eq("id", userId)
    .maybeSingle();

  if (error) throw error;
  return data ? mapProfile(data as ProfileRow) : null;
}

export async function updateProfileData(
  userId: string,
  patch: {
    name?: string;
    skills?: string[];
    interests?: string[];
    location?: string;
    org_name?: string;
  },
): Promise<void> {
  const { error } = await supabase
    .from("profiles")
    .update(patch)
    .eq("id", userId);
  if (error) throw error;
}

export async function fetchLeaderboard(): Promise<UserProfile[]> {
  const { data, error } = await supabase
    .from("profiles")
    .select("*")
    .order("trust_score", { ascending: false })
    .order("contributions_count", { ascending: false });

  if (error) throw error;
  return (data ?? []).map((row) => mapProfile(row as ProfileRow));
}

export async function fetchAllProfiles(): Promise<UserProfile[]> {
  const { data, error } = await supabase
    .from("profiles")
    .select("*");

  if (error) throw error;
  return (data ?? []).map((row) => mapProfile(row as ProfileRow));
}

// ─── Categories ──────────────────────────────────────────────────

export async function fetchCategories(): Promise<string[]> {
  const { data, error } = await supabase
    .from("categories")
    .select("name")
    .order("name");

  if (error) throw error;
  return (data ?? []).map((row) => row.name);
}

// ─── Helpers (legacy table, used for backward compat) ────────────

export interface HelperRow {
  id: string;
  code: string;
  name: string;
  email: string;
  phone: string | null;
  skills: string[];
  location: string;
  trust_score: number;
  badges: string[];
  contributions_count: number;
}

export async function fetchHelpers(): Promise<HelperRow[]> {
  const { data, error } = await supabase
    .from("helpers")
    .select("*")
    .order("trust_score", { ascending: false });

  if (error) throw error;
  return data ?? [];
}
