/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ReportIssueAssetIdRouteImport } from './routes/report-issue/$assetId'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as AssetQrCodeIdRouteImport } from './routes/asset/$qrCodeId'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMyRequestsRouteImport } from './routes/app.my-requests'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppExploreRouteImport } from './routes/app.explore'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCreateRequestRouteImport } from './routes/app.create-request'
import { Route as AppAiCenterRouteImport } from './routes/app.ai-center'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as DashboardTechnicianIndexRouteImport } from './routes/dashboard/technician/index'
import { Route as DashboardStudentIndexRouteImport } from './routes/dashboard/student/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardTechnicianAssignedTicketsRouteImport } from './routes/dashboard/technician/assigned-tickets'
import { Route as DashboardStudentReportIssueRouteImport } from './routes/dashboard/student/report-issue'
import { Route as DashboardStudentMyReportsRouteImport } from './routes/dashboard/student/my-reports'
import { Route as DashboardAdminTicketsRouteImport } from './routes/dashboard/admin/tickets'
import { Route as DashboardAdminAssetsRouteImport } from './routes/dashboard/admin/assets'
import { Route as DashboardAdminAddAssetRouteImport } from './routes/dashboard/admin/add-asset'
import { Route as AppRequestsRequestIdRouteImport } from './routes/app.requests.$requestId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ReportIssueAssetIdRoute = ReportIssueAssetIdRouteImport.update({
  id: '/report-issue/$assetId',
  path: '/report-issue/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard/_layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetQrCodeIdRoute = AssetQrCodeIdRouteImport.update({
  id: '/asset/$qrCodeId',
  path: '/asset/$qrCodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyRequestsRoute = AppMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRequestRoute = AppCreateRequestRouteImport.update({
  id: '/create-request',
  path: '/create-request',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCenterRoute = AppAiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const DashboardTechnicianIndexRoute =
  DashboardTechnicianIndexRouteImport.update({
    id: '/dashboard/technician/',
    path: '/dashboard/technician/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardStudentIndexRoute = DashboardStudentIndexRouteImport.update({
  id: '/dashboard/student/',
  path: '/dashboard/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/dashboard/admin/',
  path: '/dashboard/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTechnicianAssignedTicketsRoute =
  DashboardTechnicianAssignedTicketsRouteImport.update({
    id: '/dashboard/technician/assigned-tickets',
    path: '/dashboard/technician/assigned-tickets',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardStudentReportIssueRoute =
  DashboardStudentReportIssueRouteImport.update({
    id: '/dashboard/student/report-issue',
    path: '/dashboard/student/report-issue',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardStudentMyReportsRoute =
  DashboardStudentMyReportsRouteImport.update({
    id: '/dashboard/student/my-reports',
    path: '/dashboard/student/my-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminTicketsRoute = DashboardAdminTicketsRouteImport.update({
  id: '/dashboard/admin/tickets',
  path: '/dashboard/admin/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminAssetsRoute = DashboardAdminAssetsRouteImport.update({
  id: '/dashboard/admin/assets',
  path: '/dashboard/admin/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminAddAssetRoute = DashboardAdminAddAssetRouteImport.update({
  id: '/dashboard/admin/add-asset',
  path: '/dashboard/admin/add-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRequestsRequestIdRoute = AppRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/create-request': typeof AppCreateRequestRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/explore': typeof AppExploreRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/my-requests': typeof AppMyRequestsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/asset/$qrCodeId': typeof AssetQrCodeIdRoute
  '/dashboard': typeof DashboardLayoutRoute
  '/report-issue/$assetId': typeof ReportIssueAssetIdRoute
  '/app/': typeof AppIndexRoute
  '/app/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/dashboard/admin/add-asset': typeof DashboardAdminAddAssetRoute
  '/dashboard/admin/assets': typeof DashboardAdminAssetsRoute
  '/dashboard/admin/tickets': typeof DashboardAdminTicketsRoute
  '/dashboard/student/my-reports': typeof DashboardStudentMyReportsRoute
  '/dashboard/student/report-issue': typeof DashboardStudentReportIssueRoute
  '/dashboard/technician/assigned-tickets': typeof DashboardTechnicianAssignedTicketsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/technician/': typeof DashboardTechnicianIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/create-request': typeof AppCreateRequestRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/explore': typeof AppExploreRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/my-requests': typeof AppMyRequestsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/asset/$qrCodeId': typeof AssetQrCodeIdRoute
  '/dashboard': typeof DashboardLayoutRoute
  '/report-issue/$assetId': typeof ReportIssueAssetIdRoute
  '/app': typeof AppIndexRoute
  '/app/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/dashboard/admin/add-asset': typeof DashboardAdminAddAssetRoute
  '/dashboard/admin/assets': typeof DashboardAdminAssetsRoute
  '/dashboard/admin/tickets': typeof DashboardAdminTicketsRoute
  '/dashboard/student/my-reports': typeof DashboardStudentMyReportsRoute
  '/dashboard/student/report-issue': typeof DashboardStudentReportIssueRoute
  '/dashboard/technician/assigned-tickets': typeof DashboardTechnicianAssignedTicketsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/student': typeof DashboardStudentIndexRoute
  '/dashboard/technician': typeof DashboardTechnicianIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/create-request': typeof AppCreateRequestRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/explore': typeof AppExploreRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/my-requests': typeof AppMyRequestsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/asset/$qrCodeId': typeof AssetQrCodeIdRoute
  '/dashboard/_layout': typeof DashboardLayoutRoute
  '/report-issue/$assetId': typeof ReportIssueAssetIdRoute
  '/app/': typeof AppIndexRoute
  '/app/requests/$requestId': typeof AppRequestsRequestIdRoute
  '/dashboard/admin/add-asset': typeof DashboardAdminAddAssetRoute
  '/dashboard/admin/assets': typeof DashboardAdminAssetsRoute
  '/dashboard/admin/tickets': typeof DashboardAdminTicketsRoute
  '/dashboard/student/my-reports': typeof DashboardStudentMyReportsRoute
  '/dashboard/student/report-issue': typeof DashboardStudentReportIssueRoute
  '/dashboard/technician/assigned-tickets': typeof DashboardTechnicianAssignedTicketsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/dashboard/technician/': typeof DashboardTechnicianIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/admin'
    | '/app/ai-center'
    | '/app/create-request'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/leaderboard'
    | '/app/messages'
    | '/app/my-requests'
    | '/app/notifications'
    | '/app/profile'
    | '/asset/$qrCodeId'
    | '/dashboard'
    | '/report-issue/$assetId'
    | '/app/'
    | '/app/requests/$requestId'
    | '/dashboard/admin/add-asset'
    | '/dashboard/admin/assets'
    | '/dashboard/admin/tickets'
    | '/dashboard/student/my-reports'
    | '/dashboard/student/report-issue'
    | '/dashboard/technician/assigned-tickets'
    | '/dashboard/admin/'
    | '/dashboard/student/'
    | '/dashboard/technician/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/admin'
    | '/app/ai-center'
    | '/app/create-request'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/leaderboard'
    | '/app/messages'
    | '/app/my-requests'
    | '/app/notifications'
    | '/app/profile'
    | '/asset/$qrCodeId'
    | '/dashboard'
    | '/report-issue/$assetId'
    | '/app'
    | '/app/requests/$requestId'
    | '/dashboard/admin/add-asset'
    | '/dashboard/admin/assets'
    | '/dashboard/admin/tickets'
    | '/dashboard/student/my-reports'
    | '/dashboard/student/report-issue'
    | '/dashboard/technician/assigned-tickets'
    | '/dashboard/admin'
    | '/dashboard/student'
    | '/dashboard/technician'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/admin'
    | '/app/ai-center'
    | '/app/create-request'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/leaderboard'
    | '/app/messages'
    | '/app/my-requests'
    | '/app/notifications'
    | '/app/profile'
    | '/asset/$qrCodeId'
    | '/dashboard/_layout'
    | '/report-issue/$assetId'
    | '/app/'
    | '/app/requests/$requestId'
    | '/dashboard/admin/add-asset'
    | '/dashboard/admin/assets'
    | '/dashboard/admin/tickets'
    | '/dashboard/student/my-reports'
    | '/dashboard/student/report-issue'
    | '/dashboard/technician/assigned-tickets'
    | '/dashboard/admin/'
    | '/dashboard/student/'
    | '/dashboard/technician/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  AssetQrCodeIdRoute: typeof AssetQrCodeIdRoute
  DashboardLayoutRoute: typeof DashboardLayoutRoute
  ReportIssueAssetIdRoute: typeof ReportIssueAssetIdRoute
  DashboardAdminAddAssetRoute: typeof DashboardAdminAddAssetRoute
  DashboardAdminAssetsRoute: typeof DashboardAdminAssetsRoute
  DashboardAdminTicketsRoute: typeof DashboardAdminTicketsRoute
  DashboardStudentMyReportsRoute: typeof DashboardStudentMyReportsRoute
  DashboardStudentReportIssueRoute: typeof DashboardStudentReportIssueRoute
  DashboardTechnicianAssignedTicketsRoute: typeof DashboardTechnicianAssignedTicketsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardStudentIndexRoute: typeof DashboardStudentIndexRoute
  DashboardTechnicianIndexRoute: typeof DashboardTechnicianIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/report-issue/$assetId': {
      id: '/report-issue/$assetId'
      path: '/report-issue/$assetId'
      fullPath: '/report-issue/$assetId'
      preLoaderRoute: typeof ReportIssueAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$qrCodeId': {
      id: '/asset/$qrCodeId'
      path: '/asset/$qrCodeId'
      fullPath: '/asset/$qrCodeId'
      preLoaderRoute: typeof AssetQrCodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-requests': {
      id: '/app/my-requests'
      path: '/my-requests'
      fullPath: '/app/my-requests'
      preLoaderRoute: typeof AppMyRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create-request': {
      id: '/app/create-request'
      path: '/create-request'
      fullPath: '/app/create-request'
      preLoaderRoute: typeof AppCreateRequestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-center': {
      id: '/app/ai-center'
      path: '/ai-center'
      fullPath: '/app/ai-center'
      preLoaderRoute: typeof AppAiCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/dashboard/technician/': {
      id: '/dashboard/technician/'
      path: '/dashboard/technician'
      fullPath: '/dashboard/technician/'
      preLoaderRoute: typeof DashboardTechnicianIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student/': {
      id: '/dashboard/student/'
      path: '/dashboard/student'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof DashboardStudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/technician/assigned-tickets': {
      id: '/dashboard/technician/assigned-tickets'
      path: '/dashboard/technician/assigned-tickets'
      fullPath: '/dashboard/technician/assigned-tickets'
      preLoaderRoute: typeof DashboardTechnicianAssignedTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student/report-issue': {
      id: '/dashboard/student/report-issue'
      path: '/dashboard/student/report-issue'
      fullPath: '/dashboard/student/report-issue'
      preLoaderRoute: typeof DashboardStudentReportIssueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student/my-reports': {
      id: '/dashboard/student/my-reports'
      path: '/dashboard/student/my-reports'
      fullPath: '/dashboard/student/my-reports'
      preLoaderRoute: typeof DashboardStudentMyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/tickets': {
      id: '/dashboard/admin/tickets'
      path: '/dashboard/admin/tickets'
      fullPath: '/dashboard/admin/tickets'
      preLoaderRoute: typeof DashboardAdminTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/assets': {
      id: '/dashboard/admin/assets'
      path: '/dashboard/admin/assets'
      fullPath: '/dashboard/admin/assets'
      preLoaderRoute: typeof DashboardAdminAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/add-asset': {
      id: '/dashboard/admin/add-asset'
      path: '/dashboard/admin/add-asset'
      fullPath: '/dashboard/admin/add-asset'
      preLoaderRoute: typeof DashboardAdminAddAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/requests/$requestId': {
      id: '/app/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/app/requests/$requestId'
      preLoaderRoute: typeof AppRequestsRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiCenterRoute: typeof AppAiCenterRoute
  AppCreateRequestRoute: typeof AppCreateRequestRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExploreRoute: typeof AppExploreRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMyRequestsRoute: typeof AppMyRequestsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRequestsRequestIdRoute: typeof AppRequestsRequestIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiCenterRoute: AppAiCenterRoute,
  AppCreateRequestRoute: AppCreateRequestRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExploreRoute: AppExploreRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMyRequestsRoute: AppMyRequestsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppRequestsRequestIdRoute: AppRequestsRequestIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  AssetQrCodeIdRoute: AssetQrCodeIdRoute,
  DashboardLayoutRoute: DashboardLayoutRoute,
  ReportIssueAssetIdRoute: ReportIssueAssetIdRoute,
  DashboardAdminAddAssetRoute: DashboardAdminAddAssetRoute,
  DashboardAdminAssetsRoute: DashboardAdminAssetsRoute,
  DashboardAdminTicketsRoute: DashboardAdminTicketsRoute,
  DashboardStudentMyReportsRoute: DashboardStudentMyReportsRoute,
  DashboardStudentReportIssueRoute: DashboardStudentReportIssueRoute,
  DashboardTechnicianAssignedTicketsRoute:
    DashboardTechnicianAssignedTicketsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardStudentIndexRoute: DashboardStudentIndexRoute,
  DashboardTechnicianIndexRoute: DashboardTechnicianIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
