/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMyRequestsRouteImport } from './routes/app.my-requests'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppExploreRouteImport } from './routes/app.explore'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCreateRequestRouteImport } from './routes/app.create-request'
import { Route as AppAiCenterRouteImport } from './routes/app.ai-center'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppRequestsRequestIdRouteImport } from './routes/app.requests.$requestId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyRequestsRoute = AppMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRequestRoute = AppCreateRequestRouteImport.update({
  id: '/create-request',
  path: '/create-request',
  getParentRoute: () => AppRoute,
} as any)
const AppAiCenterRoute = AppAiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRequestIdRoute = AppRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/create-request': typeof AppCreateRequestRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/explore': typeof AppExploreRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/my-requests': typeof AppMyRequestsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/requests/$requestId': typeof AppRequestsRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/create-request': typeof AppCreateRequestRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/explore': typeof AppExploreRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/my-requests': typeof AppMyRequestsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/app/requests/$requestId': typeof AppRequestsRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-center': typeof AppAiCenterRoute
  '/app/create-request': typeof AppCreateRequestRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/explore': typeof AppExploreRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/my-requests': typeof AppMyRequestsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/requests/$requestId': typeof AppRequestsRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/admin'
    | '/app/ai-center'
    | '/app/create-request'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/leaderboard'
    | '/app/messages'
    | '/app/my-requests'
    | '/app/notifications'
    | '/app/profile'
    | '/app/'
    | '/app/requests/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/admin'
    | '/app/ai-center'
    | '/app/create-request'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/leaderboard'
    | '/app/messages'
    | '/app/my-requests'
    | '/app/notifications'
    | '/app/profile'
    | '/app'
    | '/app/requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/admin'
    | '/app/ai-center'
    | '/app/create-request'
    | '/app/dashboard'
    | '/app/explore'
    | '/app/leaderboard'
    | '/app/messages'
    | '/app/my-requests'
    | '/app/notifications'
    | '/app/profile'
    | '/app/'
    | '/app/requests/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-requests': {
      id: '/app/my-requests'
      path: '/my-requests'
      fullPath: '/app/my-requests'
      preLoaderRoute: typeof AppMyRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create-request': {
      id: '/app/create-request'
      path: '/create-request'
      fullPath: '/app/create-request'
      preLoaderRoute: typeof AppCreateRequestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-center': {
      id: '/app/ai-center'
      path: '/ai-center'
      fullPath: '/app/ai-center'
      preLoaderRoute: typeof AppAiCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests/$requestId': {
      id: '/app/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/app/requests/$requestId'
      preLoaderRoute: typeof AppRequestsRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiCenterRoute: typeof AppAiCenterRoute
  AppCreateRequestRoute: typeof AppCreateRequestRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExploreRoute: typeof AppExploreRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMyRequestsRoute: typeof AppMyRequestsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRequestsRequestIdRoute: typeof AppRequestsRequestIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiCenterRoute: AppAiCenterRoute,
  AppCreateRequestRoute: AppCreateRequestRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExploreRoute: AppExploreRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMyRequestsRoute: AppMyRequestsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppRequestsRequestIdRoute: AppRequestsRequestIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
